### ISSUE TITLE
Is the license open source?

### ISSUE THREAD

**Issue by fxcoudert** [MarcJos/Merope#2]
I came here from a LinkedIn post (https://www.linkedin.com/feed/update/urn:li:activity:7105221965300293632/): _“I’m glad to announce the availability on-line of CEA’s open-source code Mérope”_

I was looking at the repo, and the license does not appear to be open source to me. It says:

> The Licensee may not reproduce the Software in whole or in part

so as I understand it, even “forking” the project here on github would violate the license. Am I right? Could you clarify?

**Comment by MarcJos** [comment]
Dear Mr. Coudert,
The whole exerpt is :   
4.5 The Licensee may not reproduce the Software in whole or in part, regardless of the form or format of this reproduction, except: 
- as strictly required to load, display, run, transfer or store the Software for the sole purpose of its use,
- or to make one (1) backup copy, by taking all necessary precautions to avoid its disclosure,
- *or, in the case where the Licensee would use the faculty of the article 4.6, for the reproduction strictly necessary for the Licensee, to carry out  the developments of the Software.*  
4.6 The Licensee may submit to the CEA one or several developments to be integrated into a future version of the Software MEROPE. In this case, the Licensee undertakes to assign, exclusively and on a free of charge basis, to the CEA all its intellectual property rights on the integrated developments.

Therefore, due to the 3rd point of 4.5 in view of 4.6, it is allowed to fork the project on github. Yet, the developments contained in the fork would fall under this license, and thus belong to the CEA  at the moment they are published.

To my understanding (being not a lawyer), in a nutshell, Mérope is open-source but with a *more restrictive sense* than usual, with these 2 main features :
- *It belongs the CEA*, as well as its modifications.
- *Commercial use is prohibited* (unless there is a special agreement with the CEA). (The precise terms are displayed in the licence.)
It was intended that, these restrictions should have no impact *for education and research only*. I hope this is actually the case.  
With kind regards,



Marc Josien

**Comment by fxcoudert** [comment]
Thanks for confirming. I would suggest you avoid the use of “open source”, because these license terms are definitely not in line with what is called commonly called “open source”:

> Open-source software (OSS) is computer software that is released under a license in which the copyright holder grants users the rights to use, study, change, and distribute the software and its source code to anyone and for any purpose

The license would not be considered “open source” by the Open Source Initiative, either.

**Comment by MarcJos** [comment]
We were used to thinking such a licence as "open source", but thank you for underlining this misuse of the word.
Looking at the AMITEX-FFTP repository, which possesses a very similar licence, I'll therefore rather use the terms "freely available for research and education purposes".
